### ISSUE TITLE
PEERMLP of GAP architecture

### ISSUE THREAD

**Issue by Ananyaiitbhilai** [snap-research/MLPInit-for-GNNs#3]
Hey! I came across your paper MLPinit and I am trying to implement the PEERMLP for the GAP paper: https://arxiv.org/abs/2203.00949

I aim to apply transfer learning on GAP to achieve the same privacy budget in less number of epochs.

The proposed MLPInit method does not even need extra data for pre-training. I can simply use the node features to train the PeerMLP of GAP and then use its learned weights to initialize GAP. Under edge-level DP, this approach does not incur any privacy costs.

Could you please guide me on How can I make changes in the GAP code and train its PEERMLP? 
GAP repo: https://github.com/sisaman/GAP

**Comment by ahxt** [comment]
Thank you for your question. For a simple application of our method, I would recommend changing the adjacency matrix A of the input graph to an identity matrix I. Note that this approach might not result in reduced training time.
